# Generated by Django 5.0.1 on 2024-01-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                default="blog/default.png", upload_to="blog/images/"
            ),
        ),
    ]
