# Generated by Django 5.0.1 on 2024-01-11 10:59

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
